version: 'latest'

services:
  spark:
    image: docker.io/bitnami/spark:latest
    hostname: master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      # - /home/pubserver/spark/commondata:/opt/share
      - /E/QQfiles/bigdata-training/lesson-big-data-training:/opt/share
    ports:
      - '8080:8080'
      - '4040:4040'
    networks:
      sparknet:
        ipv4_address: 172.22.0.100
    extra_hosts:
      - "master:172.22.0.100"
      - "worker1:172.22.0.101"
      - "worker2:172.22.0.102"
  spark-worker-1:
    image: docker.io/bitnami/spark:latest
    hostname: worker1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - /E/QQfiles/bigdata-training/lesson-big-data-training:/opt/share
    ports:
      - '8081:8081'
    networks:
      sparknet:
        ipv4_address: 172.22.0.101
    extra_hosts:
      - "master:172.22.0.100"
      - "worker1:172.22.0.101"
      - "worker2:172.22.0.102"
  spark-worker-2:
    image: docker.io/bitnami/spark:latest
    hostname: worker2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - /E/QQfiles/bigdata-training/lesson-big-data-training:/opt/share
    ports:
      - '8082:8081'
    networks:
      sparknet:
        ipv4_address: 172.22.0.102
    extra_hosts:
      - "master:172.22.0.100"
      - "worker1:172.22.0.101"
      - "worker2:172.22.0.102"
networks:
  sparknet:
    driver: bridge
    ipam:
      config:
        - subnet: "172.22.0.0/24"